### ISSUE TITLE
Feedback: test it and one absurd example

### ISSUE THREAD

**Issue by daniel-pfeiffer** [canonical/rust-best-practices#7]
To avoid code typos like “speces” feed it to `cargo test` with

```rust
// lib.rs

#![doc = include_str!("../best-practices.md")]
```

And “Increment a counter by a given amount.” is the vaguest of explanations (some counter somewhere & some given amount somewhere, go guess whether that might be self & delta.) It directly contradicts the sentence before, saying to prefer “the” and even that is less clear than your avoid-example.

**Comment by TheSignPainter98** [comment]
Thanks for the suggestion to test this! I hadn't realised this was possible, but it seems like an excellent addition so I'll take a look into it. Unfortunately this will require some work as for the sake of brevity, many of the snippets omit definitions of values they use, so it will be an interesting challenge to keep it both testable and legible. (Perhaps a migration to `mdbook` is inevitable...)

For the second part of the issue, it seems that I mixed up the order of the recommendations, the 'avoid this' example is actually the 'do this' example. Thanks for spotting the mistake! I'll get it fixed

**Comment by daniel-pfeiffer** [comment]
You can add an ignore after the 3 backticks and later gradually improve on that.

**Comment by TheSignPainter98** [comment]
I've gone through all snippets and tested them with `mdbook test` (this has also been added to CI). The incorrect comment recommendation has also been fixed. Thanks for the issue!
